---
title: "assess_downscaling"
output: html_document
---
```{r}
 # rm(list = ls())
  if (!"zoo" %in% installed.packages()) install.packages("zoo")
  library(zoo)
  if (!"imputeTS" %in% installed.packages()) install.packages("imputeTS")
  library(imputeTS)
  if (!"lubridate" %in% installed.packages()) install.packages("lubridate")
  library(lubridate)
  library(tidyr)
  library(dplyr)
  library(ggplot2)
  library(stringr) # used in assess_downscaling to create filename
  library(dplyr)
  path.my.files = "/Users/laurapuckett/Documents/Research/Fall 2018/my_files/"
  source(paste(path.my.files, "solar_geom.R", sep = ""))
  source(paste(path.my.files, "daily_debias_from_coeff.R", sep = ""))
  source(paste(path.my.files, "add_noise.R", sep = ""))
  source(paste(path.my.files, "new_spline_NOAA_offset.R", sep = ""))
  source("/Users/laurapuckett/Documents/Research/Fall 2018/my_files/prep_obs.R")
  source("/Users/laurapuckett/Documents/Research/Fall 2018/my_files/check_CI.R")

  #process_GEFS2GLM <- function(in_directory,out_directory,file_name,input_tz = 'EST5EDT',output_tz = 'GMT'){
  
  # file_name = "20181118gep_all_00z" # temporary just to be able to run something
  in_directory = "/Users/laurapuckett/Documents/Research/Fall 2018/my_files/SCCData-noaa-data/"
  out_directory = "/Users/laurapuckett/Documents/Research/Fall 2018/my_files/met_output_files"
```

```{r setup, include=FALSE}
START_TIME = "2018-11-18 00:19:00 UTC"
END_TIME = "2018-12-02 00:19:00 UTC"
```

```{r out of box, 1 day}
sum.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(0,5),
                                      mean.residual = rep(0,5),
                                      CI.90 = rep(0,5),
                                      CI.95 = rep(0,5),
                                      CI.100 = rep(0,5))

mean.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(NA,5),
                                      mean.residual = rep(NA,5),
                                      CI.90 = rep(NA,5),
                                      CI.95 = rep(NA,5),
                                      CI.100 = rep(NA,5))
count = 0
for (i in 0:13){
  table.i = assess_downscaling(start_time = as_datetime(START_TIME) + 24*60*60 * i,
                               end_time = as_datetime(START_TIME) +  24*60*60 * (i + 1),
                               DOWNSCALE_MET = FALSE, ###
                               ADD_NOISE = FALSE,
                               PLOT = FALSE,
                               PRINT = FALSE) # iterating one day at a time, 1-day intervals
  for(n in 1:nrow(table.i)){
    for(m in 2:ncol(table.i)){
      sum.table[n,m] = sum.table[n,m] + table.i[n,m]
    }
  }
  count = count + 1
}
  for(n in 1:nrow(sum.table)){
    for(m in 2:ncol(sum.table)){
      mean.table[n,m] = sum.table[n,m]/count
    }
  }

out.of.box.1.day = mean.table
```
```{r ds no noise, 1 day}
sum.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(0,5),
                                      mean.residual = rep(0,5),
                                      CI.90 = rep(0,5),
                                      CI.95 = rep(0,5),
                                      CI.100 = rep(0,5))

mean.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(NA,5),
                                      mean.residual = rep(NA,5),
                                      CI.90 = rep(NA,5),
                                      CI.95 = rep(NA,5),
                                      CI.100 = rep(NA,5))
count = 0
for (i in 0:13){
  table.i = assess_downscaling(start_time = as_datetime(START_TIME) + 24*60*60 * i,
                               end_time = as_datetime(START_TIME) +  24*60*60 * (i + 1),
                               DOWNSCALE_MET = TRUE, ###
                               ADD_NOISE = FALSE, ###
                               PLOT = FALSE,
                               PRINT = FALSE) # iterating one day at a time, 1-day intervals
  for(n in 1:nrow(table.i)){
    for(m in 2:ncol(table.i)){
      sum.table[n,m] = sum.table[n,m] + table.i[n,m]
    }
  }
  count = count + 1
}
  for(n in 1:nrow(sum.table)){
    for(m in 2:ncol(sum.table)){
      mean.table[n,m] = sum.table[n,m]/count
    }
  }

ds.no.noise.1.day = mean.table
```

```{r ds with noise, 1 day}
sum.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(0,5),
                                      mean.residual = rep(0,5),
                                      CI.90 = rep(0,5),
                                      CI.95 = rep(0,5),
                                      CI.100 = rep(0,5))

mean.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(NA,5),
                                      mean.residual = rep(NA,5),
                                      CI.90 = rep(NA,5),
                                      CI.95 = rep(NA,5),
                                      CI.100 = rep(NA,5))
count = 0
for (i in 0:13){
  table.i = assess_downscaling(start_time = as_datetime(START_TIME) + 24*60*60 * i,
                               end_time = as_datetime(START_TIME) +  24*60*60 * (i + 1),
                               DOWNSCALE_MET = TRUE, ###
                               ADD_NOISE = TRUE, ###
                               PLOT = FALSE,
                               PRINT = FALSE) # iterating one day at a time, 1-day intervals
  for(n in 1:nrow(table.i)){
    for(m in 2:ncol(table.i)){
      sum.table[n,m] = sum.table[n,m] + table.i[n,m]
    }
  }
  count = count + 1
}
  for(n in 1:nrow(sum.table)){
    for(m in 2:ncol(sum.table)){
      mean.table[n,m] = sum.table[n,m]/count
    }
  }

ds.with.noise.1.day = mean.table
```


```{r average 3-day performance over 16 days withheld}
old.results = results
sum.3day.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(0,5),
                                      mean.residual = rep(0,5),
                                      CI.90 = rep(0,5),
                                      CI.95 = rep(0,5),
                                      CI.100 = rep(0,5))
mean.3day.table = data_frame(metric = c("temp","RH","ws","sw","lw"),
                                      r2 = rep(NA,5),
                                      mean.residual = rep(NA,5),
                                      CI.90 = rep(NA,5),
                                      CI.95 = rep(NA,5),
                                      CI.100 = rep(NA,5))
count = 0
for (i in 0:12){ # once I load in more data, this should be 16 days not 13
  table.i = assess_downscaling(start_time = as_datetime(START_TIME) + 24*60*60 * i,
                               end_time = as_datetime(START_TIME) +  24*60*60 * (i + 3),
                               DOWNSCALE_MET = TRUE,
                               ADD_NOISE = FALSE,
                               PLOT = FALSE,
                               PRINT = TRUE) # iterating one day at a time, 3-day intervals
  for(n in 1:nrow(sum.3day.table)){
    for(m in 2:ncol(sum.3day.table)){
      sum.3day.table[n,m] = sum.3day.table[n,m] + table.i[n,m]
    }
  }
  count = count + 1
}
  for(n in 1:nrow(sum.3day.table)){
    for(m in 2:ncol(sum.3day.table)){
      mean.3day.table[n,m] = sum.3day.table[n,m]/count
    }
  }
print(mean.3day.table)
```

```{r 16 day performance}
out.of.box.16.days = assess_downscaling(start_time = "2018-11-18 00:19:00 UTC",
                             end_time = "2018-12-02 00:19:00 UTC",
                             DOWNSCALE_MET = FALSE, ###
                             ADD_NOISE = TRUE,
                             PLOT = TRUE,
                             PRINT = TRUE)
out.of.box.16.days
ds.no.noise.16.days = assess_downscaling(start_time = "2018-11-18 00:19:00 UTC",
                             end_time = "2018-12-02 00:19:00 UTC",
                             DOWNSCALE_MET = TRUE, ###
                             ADD_NOISE = FALSE, ###
                             PLOT = TRUE,
                             PRINT = TRUE)
ds.no.noise.16.days
ds.with.noise.16.days = assess_downscaling(start_time = "2018-11-18 00:19:00 UTC",
                             end_time = "2018-12-02 00:19:00 UTC",
                             DOWNSCALE_MET = TRUE, ###
                             ADD_NOISE = TRUE, ###
                             PLOT = TRUE,
                             PRINT = TRUE)
ds.with.noise.16.days
```
